setwd("C:/Users/50568/Desktop")
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
total_emissions_by_year <- with(NEI, tapply(Emissions, year, sum, na.rm = T))
year <- as.numeric(names(total_emissions_by_year))
total_emissions <- unname(total_emissions_by_year[1:length(total_emissions_by_year)])
total_emissions_by_year <- data.frame(year, total_emissions)
png(file="plot1.png", width=480, height=480)
with(total_emissions_by_year, {plot(year, total_emissions, xlab = "Year", ylab=" PM2.5 Emissions", type='l', pch=19, xlim = c(1999, 2008), xaxt = "n")
  axis(side = 1, at = year, labels = year)})
title(main = "Total PM2.5 Emissions for each year")
dev.off()
